#!/usr/bin/env bash
# Script that configures an Ubuntu server

if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root (use sudo)"
    exit 1
fi

cp /etc/hosts /etc/hosts.new

sed -i 's/127.0.0.1\slocalhost/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts

exit 0
