#!/usr/bin/env bash
# Script that configures an Ubuntu server

if [ "$EUID" -ne 0 ]; then
    echo "This script must be run as root (use sudo)"
    exit 1
fi

cp /etc/hosts /etc/hosts.bak

sed -i '/localhost/d' /etc/hosts
sed -i '/facebook.com/d' /etc/hosts

echo "127.0.0.2 localhost" >> /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

exit 0
